services:
  - type: web
    name: doctor-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: DB_HOST
        sync: false

      - key: DB_PORT
        value: "26769"

      - key: DB_NAME
        value: defaultdb

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false

      - key: JWT_SECRET_KEY
        generateValue: true